<?php

/**
 * @file
 * Code for the Stanford Paragraph Types Dynamic feature.
 */

include_once 'stanford_paragraph_types_dynamic.features.inc';

/**
 * Implements hook_theme().
 */
function stanford_paragraph_types_dynamic_theme($existing, $type, $theme, $path) {
  return stanford_paragraph_types_theme_templates($existing, 'stanford_paragraph_types_dynamic');
}

/**
 * Implements hook_preprocess_field().
 */
function stanford_paragraph_types_dynamic_preprocess_field(&$vars) {
  if ($vars['element']['#field_name'] == 'field_p_views_view') {
    $items = count($vars['items']);
    if ($items <= 6) {
      $class = 'span' . floor(12 / $items);
    }
    else {
      $class = 'span2';
    }
    $vars['item_class'] = $class;
  }
}

/**
 * Implements hook_field_attach_form().
 */
function stanford_paragraph_types_dynamic_field_attach_form($entity_type, $entity, &$form, &$form_state, $langcode) {
  foreach (element_children($form) as $field_name) {
    if ($instance = field_info_instance($entity_type, $field_name, $form['#bundle'])) {
      // Add remove button to multiple selects widget.
      if ($instance['widget']['type'] == 'multiple_selects') {
        foreach (element_children($form[$field_name][LANGUAGE_NONE]) as $delta) {

          $element = &$form[$field_name][LANGUAGE_NONE][$delta];
          if (isset($element['#type']) && $element['#type'] == 'submit') {
            continue;
          }

          $parents = $element['#field_parents'];
          $parents[] = $field_name;
          $parents[] = LANGUAGE_NONE;
          $parents[] = $delta;

          $parents = implode('_', $parents);
          $element['remove_button'] = array(
            '#delta' => $delta,
            '#name' => $parents . '_remove_button',
            '#type' => 'submit',
            '#value' => t('Remove'),
            '#validate' => array(),
            '#submit' => array('stanford_paragraph_types_link_remove_submit'),
            '#limit_validation_errors' => array(),
            '#weight' => 1000,
            '#ajax' => array(
              'effect' => 'fade',
              'callback' => 'stanford_paragraph_types_link_remove_callback',
              'wrapper' => $form[$field_name][LANGUAGE_NONE]['add_more']['#ajax']['wrapper'],
            ),
          );
        }
      }
    }
  }
}

/**
 * Implements hook_preprocess_entity_paragraphs_item().
 */
function stanford_paragraph_types_dynamic_preprocess_entity(&$vars) {
  if ($vars['elements']['#entity_type'] == 'paragraphs_item') {
    $entity = $vars['elements']['#entity'];
    switch ($entity->bundle) {
      case 'p_views':
        $vars['classes_array'][] = 'span12';
        $vars['classes_array'][] = 'center';
        break;
    }
  }
}
