<?php

/**
 * @file
 * stanford_paragraph_video.module
 */

/**
 * Implements hook_preprocess_field().
 */
function stanford_paragraph_video_preprocess_field(&$variables) {
  if ($variables['field_name'] != 'field_p_video_url') {
    return;
  }

  /** @var \Drupal\Core\Field\FieldItemList $autoplay_field */
  $autoplay_field = $variables['element']['#object']->get('field_p_video_autoplay');

  if ($autoplay_field && $autoplay_field->getValue()) {
    $autoplay = $autoplay_field->getValue();

    // If the paragraph is checked to autoplay, set the query parameter.
    if ($autoplay[0]['value']) {
      $variables['items'][0]['content']['children']['#query']['autoplay'] = TRUE;
      $variables['items'][0]['content']['children']['#query']['showinfo'] = FALSE;
      $variables['items'][0]['content']['children']['#query']['rel'] = FALSE;
    }
  }
}
